# Generated by Django 2.0.9 on 2018-10-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/img/default.png', upload_to='img/'),
        ),
    ]
